name: Test and changelog
on:
  push:
jobs:
#  test:
#
  changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
#        with:
#          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install gitchangelog
        run: pip install gitchangelog pystache

      - name: Create changelog
        run: gitchangelog > ./CHANGELOG.md

      - name: Upload changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CHANGELOG.md
